#!/bin/bash
# Quick script to help upload indexes to Render

echo "📦 Render Index Upload Helper"
echo "=============================="
echo ""

# Check if zip exists
if [ ! -f "clinical-ai-indexes.zip" ]; then
    echo "❌ Error: clinical-ai-indexes.zip not found!"
    echo "Run ./prepare-indexes.sh first to create it."
    exit 1
fi

echo "✅ Found: clinical-ai-indexes.zip"
echo "   Size: $(du -sh clinical-ai-indexes.zip | cut -f1)"
echo ""
echo "📋 Upload Instructions for Render:"
echo ""
echo "1. Go to Render Dashboard: https://dashboard.render.com"
echo "   └─ Select your 'clinical-ai-backend' service"
echo ""
echo "2. Click 'Shell' tab (top navigation)"
echo "   └─ Wait for shell to connect (green status)"
echo ""
echo "3. In the shell, run:"
echo "   cd /app/indexes"
echo "   pwd    # Should show: /app/indexes"
echo ""
echo "4. Upload file:"
echo "   └─ Look for 'Upload' button in shell interface"
echo "   └─ OR use the file path shown in shell"
echo "   └─ Select: $(pwd)/clinical-ai-indexes.zip"
echo ""
echo "5. Extract in Render shell:"
echo "   unzip clinical-ai-indexes.zip"
echo "   ls -la    # Verify 9 files"
echo "   rm clinical-ai-indexes.zip    # Clean up"
echo ""
echo "6. Restart service:"
echo "   └─ Go back to dashboard"
echo "   └─ Click 'Manual Deploy' → 'Clear build cache & deploy'"
echo ""
echo "7. Verify it worked:"
echo "   └─ Visit: https://your-backend.onrender.com/health"
echo "   └─ Should show all 4 domains loaded"
echo ""
echo "=============================="
echo "📍 File ready at:"
echo "   $(pwd)/clinical-ai-indexes.zip"
echo ""
echo "💡 Tip: Keep this terminal open for easy copy-paste!"
echo ""
